author:
  name: Steve Norris
  email: stevenorris41@gmail.com
title: Documented Through Art
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/b94fa3bb-7bb9-473b-be4b-3bef3ffb138d.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a56d301-49ed-4003-adc4-c482e6c5ff1e.jpg
color:
  saturation: 0.9657200544606894
  brandStrength: 0.32277054945006967
  lightness: 0.6844672525767237
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  rhythmicContrast: 0.002730141393840313
typography_spectrum: 0.568560291081667
layout_spectrum: 0.8241720758378506
content_rating:
  adult: false
name: The Rock Poster
