author:
  name: Steve Norris
  email: stevenorris41@gmail.com
title: Documented Through Art
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/b94fa3bb-7bb9-473b-be4b-3bef3ffb138d.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a56d301-49ed-4003-adc4-c482e6c5ff1e.jpg
color:
  saturation: 1
  brandStrength: 0.5985663
  lightness: 0.7867383
  brandColors:
    - '#0F1217'
    - '#525C68'
    - '#009EAC'
    - '#C0DAF3'
    - '#FBFF84'
  rhythmicContrast: 1
typography_spectrum: 0.1957652745768428
layout_spectrum: 0.9426523
content_rating:
  adult: false
name: The Rock Poster
