typography_spectrum: 0.19576527457684278
content_rating:
  adult: false
color:
  brandStrength: 0.5806072175037116
  lightness: 0.21639863308519125
  saturation: 0.5792650820221752
  rhythmicContrast: 0.011866291286423802
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/b94fa3bb-7bb9-473b-be4b-3bef3ffb138d.jpg
layout_spectrum: 0.428412685636431
author:
  name: Steve Norris
  email: stevenorris41@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a56d301-49ed-4003-adc4-c482e6c5ff1e.jpg
name: The Rock Poster
