title: Documented Through Art
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8082438
  brandStrength: 0.5412186
  lightness: 0.6021506
  brandColors:
    - '#8D95B9'
    - '#070908'
    - '#033420'
    - '#544E56'
    - '#DFE7EA'
  rhythmicContrast: 0.1971326
name: The Rock Poster
author:
  name: Steve Norris
  email: stevenorris41@gmail.com
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/b94fa3bb-7bb9-473b-be4b-3bef3ffb138d.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8a56d301-49ed-4003-adc4-c482e6c5ff1e.jpg
typography_spectrum: 0.568560291081667
layout_spectrum: 0.5860215
content_rating:
  adult: false
